### ISSUE TITLE
Demon's dream huge fps lag with unstable otherworld tree 

### ISSUE THREAD

**Issue by uiytt** [klikli-dev/occultism#404]
**Describe the bug**
When you eat Demon's Fruit next to a lot of unstable otherworld tree (~15), you lost around 200 fps  

**To Reproduce**
1. Grow around 15 unstable otherworld tree next to each others
2. Eat demon's fruit
3. Lose 200 fps
4. **OTHERWORLD GOGGLES works fine**

**Expected behavior**
Almost no lag like Otherworld goggles.

**System (please complete the following information):**
- Occultism Version: 1.11.3
- OS: Ubuntu (linux)
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Curios API (1.16.5-4.0.5.3) & Patchouli (1.16.4-53.1) 

**Additional context**
Discovered this problem in otherworld groves

**Comment by klikli-dev** [comment]
Goggles and demon's dream actually work the same way internally, except that the fruit is using a shader.

Can you try to set `disableDemonsDreamShaders` to `true` in the client config occultism-client.toml and let me know if the issues persist? 
```toml 
[visual]
#Disables the headache- and possibly seizure-inducing visual effects of Demon's Dream.
disableDemonsDreamShaders = true
```
