### ISSUE TITLE
Feature Request: Custom spirit names

### ISSUE THREAD

**Issue by atlgeek007** [klikli-dev/occultism#702]
**Is your feature request related to a problem? Please describe.**
It's not related to an issue/problem at all, just flavor.

**Describe the solution you'd like**
I would like the ability to give the mod a list of custom names to pull from rather than what's hardcoded.  I'm working on a modded server for a friend's twitch community and would like to have spirits/etc named after mods/vips in that community, but as I understand it all the current names are hardcoded.

**Additional context**
N/A :)

**Comment by klikli-dev** [comment]
Configurable in `/saves/<world>/serverconfig/occultism-server.toml`

```toml
#Ritual Settings
[rituals]
	#By default spirit names are generated at random from lists of possible syllables.
	#If you instead want to specify the possible spirit names directly, configure a list of values here.
	possibleSpiritNames = ["atlgeek007", "VIP-2", "..."]
```

Will be available in https://github.com/klikli-dev/occultism/releases/tag/release%2Fv1.18.2-1.32.1
